Repository open-xchange/ox-coi, pull requests merged in 2020-01, with the labels that each got.

#351 OT-598 No Option to add an unblocked unknown user to contacts
  lib/src/contact/contact_change_bloc.dart
Labels: warning

#370 Flickering on swipe to delete / block #366
  lib/src/chat/chat_create.dart
  lib/src/chatlist/chat_list.dart
  lib/src/chatlist/chat_list_item.dart
  lib/src/contact/contact_blocked_list.dart
  lib/src/contact/contact_item.dart
  lib/src/contact/contact_list.dart
  lib/src/ui/dimensions.dart
  lib/src/widgets/avatar_list_item.dart
  pubspec.yaml
Labels: bug

#385 Issue-379: Support for multiple GoogleService-Info.plist files
  ios/Flutter/Debug-development.xcconfig
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release-development.xcconfig
  ios/Flutter/Release-stable.xcconfig
  ios/Flutter/Release.xcconfig
  ios/OX Coi/Application/AppDelegate.swift
  ios/OX Coi/Extensions/UIKit/UIApplication+Firebase.swift
  ios/OX Coi/Firebase/GoogleService-Info-Development.plist
  ios/OX Coi/Firebase/GoogleService-Info-Production.plist
  ios/OX Coi/Info.plist
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner.xcodeproj/xcshareddata/xcschemes/development.xcscheme
  ios/Runner.xcodeproj/xcshareddata/xcschemes/stable.xcscheme
  ios/exportOptionsstable.plist
  tools/build.triggerBuild.sh
Labels: iOS
